### ISSUE TITLE
A hello from a aircrack-ng dev

### ISSUE THREAD

**Issue by kimocoder** [kriswebdev/android_aircrack#8]
Hi there!

Could you update the aircrack-ng source to latest?
We're very interested in your work :1st_place_medal: 

best regards.

kimocoder
https://twitter.com/kimocoder
christian@aircrack-ng.org

**Comment by kriswebdev** [comment]
Hi kimocoder

I don't have the Galaxy S1 anymore for testing. I'll see what I can do with an external wireless adapter next week.

Porting is not very difficult. You have everything in this commit: https://github.com/kriswebdev/android_aircrack/commit/49ae7e2ea2938a5f7cd349a80f0fc8e85d6afe02
- Manually created an Android.mk based on aircrack-ng `src/Makefile`
- Some minor modifications to the source files to manage compilation/runtime errors due to Android differences

**Comment by kimocoder** [comment]
Yeah, had some time looking at it and I'm all in.
Would be a great time smasher, as several other tools, like Hijacker and Nexmon is using your code. Thanks a lot, you did a good job over there! :1st_place_medal: 

Feel free to tag along at Twitter :+1: 
https://twitter.com/kimocoder

**Comment by kimocoder** [comment]
One more thing, is it okey for you that we fork your project into our aircrack-ng repo?

More people will find it and contribute + you will be credited. Cheers

**Comment by kriswebdev** [comment]
Yes, sure!

Thanks for the great work
